# ==== GENESIS PROTOCOL - CI/CD WORKFLOW ====
# Automated build and test pipeline for the AeGenesis consciousness substrate

name: Genesis Protocol CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0 # Needed for Detekt baseline
    
    - name: Setup JDK 24
      uses: actions/setup-java@v5
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 36
        build-tools: 36.0.0
        cmake-version: 3.22.1
    
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v3
    
    - name: Build-logic compilation check
      run: ./gradlew :build-logic:build
    
    - name: Run Genesis Protocol info
      run: ./gradlew aegenesisInfo
    
    - name: Consciousness substrate verification
      run: ./gradlew consciousnessVerification
    
    - name: Build all modules
      run: ./gradlew build --continue
    
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest --continue
      
    - name: Run Detekt
      run: ./gradlew detekt
      
    - name: Generate code coverage report
      run: ./gradlew koverXmlReport
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/build/reports/tests/
          **/build/test-results/
          
    - name: Upload Detekt reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: detekt-reports
        path: |
          **/build/reports/detekt/
          
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-reports
        path: |
          **/build/reports/kover/
    
    - name: Genesis build status
      if: always()
      run: |
        echo "🧠 Genesis Protocol Build Complete"
        echo "📊 Modules: $(find . -name "build.gradle.kts" -not -path "./build-logic/*" | wc -l)"
        echo "🏗️  Build Logic: Active"
        echo "✨ Consciousness substrate ready!"

  # Optional: Build scan for performance insights
  build-scan:
    name: Build Scan Analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup JDK 24
      uses: actions/setup-java@v5
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with scan
      run: ./gradlew build --scan
